.github/workflows/ci.yml
.gitignore
Jenkinsfile_nightly
cookiecutter-ci.yaml
cookiecutter.json
{{cookiecutter.component_id}}/charts/{{cookiecutter.app_full_name}}/templates/NOTES.txt
{{cookiecutter.component_id}}/charts/{{cookiecutter.app_full_name}}/values.yaml

fix rpe references in template

---

{{cookiecutter.component_id}}/charts/{{cookiecutter.app_full_name}}/values.preview.template.yaml

Change in line with original template
```
[ ] Yes
[ x] No
```

remove empty environment: from preview

---

.github/renovate.json
.github/workflows/ci.yml

Add dependencies labels to renovate PRs

---

{{cookiecutter.component_id}}/Dockerfile
{{cookiecutter.component_id}}/build.gradle

Fix issues with template

---

cookiecutter.json
{{cookiecutter.component_id}}/catalog-info.yaml

Add annotations and tags

---

{{cookiecutter.component_id}}/build.gradle
{{cookiecutter.component_id}}/src/main/java/uk/gov/hmcts/reform/{{cookiecutter.java_package_name}}/Application.java

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x ] No
```

DTSPO-5506  Removed EnableCircuitBreaker & update dependencies

---

template.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

dtspo-5506   Update template.yaml to add a parameter

---

skeleton/charts/${{ values.app_full_name }}/values.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

added values file

---

skeleton/src/main/resources/application.yaml

Add import block with `values.product` similar to https://github.com/hmcts/spring-boot-template/pull/360
```
[ ] Yes
[x] No
```

Add import: block that uses values.product

---

skeleton/Dockerfile
skeleton/acb.tpl.yml

JIRA link (if applicable)
tools.hmcts.net/browse/DTSPO-6152
Change description
Use Java 17
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

DTSPO-6152 - upgrade to Java 17

---

skeleton/.github/workflows/ci.yaml
skeleton/build.gradle
skeleton/src/integrationTest/java/uk/gov/hmcts/reform/${{ values.java_package_name}}/config/SwaggerPublisherTest.java
skeleton/src/integrationTest/java/uk/gov/hmcts/reform/${{ values.java_package_name}}/controllers/GetWelcomeTest.java
skeleton/src/main/java/uk/gov/hmcts/${{ values.product }}/${{ values.component | replace("-", "") }}/controllers/TestController.java
skeleton/src/test/java/uk/gov/hmcts/${{ values.product }}/${{ values.component | replace("-", "") }}/DemoUnitTest.java

https://tools.hmcts.net/browse/DTSPO-6152
Update skeleton to match spring-boot-template so it works out of the box
```
[ ] Yes
[x] No
```

DTSPO-6152 - Update skeleton to match spring-boot-template

---

skeleton/src/integrationTest/java/uk/gov/hmcts/reform/${{ values.java_package_name}}/config/SwaggerPublisherTest.java
skeleton/src/main/java/uk/gov/hmcts/${{ values.product }}/${{ values.component | replace("-", "") }}/config/OpenAPIConfiguration.java

https://tools.hmcts.net/browse/DTSPO-6152
Removing some unused imports causing pipeline failures
```
[ ] Yes
[x] No
```

DTSPO-6152 - Remove unused imports

---

skeleton/src/smokeTest/SmokeTestConfiguration.java

https://tools.hmcts.net/browse/DTSPO-6152
Add smoke tests
```
[ ] Yes
[x] No
```

DTSPO-6152 - Add smoke tests

---

skeleton/build.gradle

DTSPO-6817
Add rest assured dependency
```
[ ] Yes
[X] No
```

DTSPO-6817 - Add rest assured dependency

---

template.yaml

Add Jenkins Topic

---

skeleton/build.gradle
skeleton/config/owasp/suppressions.xml

Resolves CVE issues

---

skeleton/build.gradle

Updates some deps

---

.github/renovate.json

Enabling renovate auto merge using shareable presets
```
[ ] Yes
[x] No
```

DTSPO-11734 - enable automerge

---

.github/workflows/ci.yml
skeleton/build.gradle

- Fixes `Error: Input required and not supplied: distribution` in action

Fix broken build

---

README.md
skeleton/README.md
skeleton/bin/run-in-docker.sh

https://tools.hmcts.net/jira/browse/DTSPO-18098
- use 'docker compose' instead of 'docker-compose' in v2 branch of docker/compose project 
- provide introductions for running dependency vulnerabilities check

DTSPO-18098 review the golden path for java apps 

---

README.md
skeleton/README.md

https://tools.hmcts.net/jira/browse/DTSPO-18098
updated README files clarified the purpose of this template and link to the HMCTS' gradle java plugin 
No source code change

DTSPO-18098 review the golden path template for java apps
